### ISSUE TITLE
Lab 4 task 4: Run complex operations on your data (New stored procedure)

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#23]
Error when try to execute new stored procedure "createMyDocument". I am ale to Save the new procedure but after I click Execute In the Input Parameters screen, type should be set to string, and value set to 33218898 in the Partition Key Value text box, and then click Execute.. I get an error.

{"code":400,"body":{"code":"BadRequest","message":"Message: {\"Errors\":[\"Encountered exception while executing f

Failed to execute stored procedure createMyDocument for container Clothing: {"code":400,"body":{"code":"BadRequest","message":"Message: {\"Errors\":[\"Encountered exception while executing function. Exception = Error: Error{\\\"Errors\\\":[\\\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\\\"]}\\r\\nStack trace: Error: Error{\\\"Errors\\\":[\\\"Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted.\\\"]}\\n   at Anonymous function (script.js:14:18)\\n   at Anonymous function (script.js:685:29)\"]}\r\nActivityId: ac0e5e8c-b460-4562-9e55-18b26c715232, Request URI: /apps/5c61adcc-91a7-4170-80b9-21ba2ebb223e/services/dce4cd1a-3e2c-4bdc-a2e0-7c7c533ecb72/partitions/d625091d-b576-48b4-8af8-c8962b0d8717/replicas/132152985852543079p, RequestStats: \r\nRequestStartTime: 2019-10-14T13:13:26.5425589Z, RequestEndTime: 2019-10-14T13:13:26.5425589Z,  Number of regions attempted:1\r\nResponseTime: 2019-10-14T13:13:26.5425589Z, StoreResult: StorePhysicalAddress: rntbd://10.0.0.129:16700/apps/5c61adcc-91a7-4170-80b9-21ba2ebb223e/services/dce4cd1a-3e2c-4bdc-a2e0-7c7c533ecb72/partitions/d625091d-b576-48b4-8af8-c8962b0d8717/replicas/132152985852543079p, LSN: 11, GlobalCommittedLsn: 11, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 2.86, ItemLSN: -1, SessionToken: -1#11, UsingLocalLSN: False, TransportException: null, ResourceType: StoredProcedure, OperationType: ExecuteJavaScript\r\n, SDK: Microsoft.Azure.Documents.Common/2.7.0"},"headers":{"access-control-allow-credentials":"true","access-control-allow-origin":"https://cosmos.azure.com","content-type":"application/json","lsn":"11","strict-transport-security":"max-age=31536000","x-ms-activity-id":"ac0e5e8c-b460-4562-9e55-18b26c715232","x-ms-cosmos-llsn":"11","x-ms-cosmos-quorum-acked-llsn":"11","x-ms-current-replica-set-size":"4","x-ms-current-write-quorum":"3","x-ms-gatewayversion":"version=2.7.0","x-ms-global-committed-lsn":"11","x-ms-last-state-change-utc":"Fri, 11 Oct 2019 20:16:37.536 GMT","x-ms-number-of-read-regions":"0","x-ms-quorum-acked-lsn":"11","x-ms-request-charge":"2.86","x-ms-schemaversion":"1.8","x-ms-serviceversion":"version=2.7.0.0","x-ms-session-token":"0:-1#11","x-ms-transport-request-id":"27","x-ms-xp-role":"1","x-ms-throttle-retry-count":0,"x-ms-throttle-retry-wait-time-ms":0},"activityId":"ac0e5e8c-b460-4562-9e55-18b26c715232"}

**According to the instruction:**

In the Azure portal, in the Items screen, click on the button New Stored Procedure.

Note: A New Stored Procedure screen appears which shows a sample stored procedure .

In the New Stored Procedure screen, in the Stored Procedure Id text box, type createMyDocument.

Use the following code to create a stored procedure in the Stored Procedure Body.

Javascript
function createMyDocument() {
    var context = getContext();
    var collection = context.getCollection();
var doc = {
    "id": "3",
    "productId": "33218898",
    "description": "Contoso microfleece zip-up jacket",
    "price": "44.99"
};

var accepted = collection.createDocument(collection.getSelfLink(),
    doc,
    function (err, documentCreated) {
        if (err) throw new Error('Error' + err.message);
        context.getResponse().setBody(documentCreated)
    });
if (!accepted) return;
}
In the New Stored Procedure screen, click Save.

In the New Stored Procedure screen, click Execute.

In the Input Parameters screen, type should be set to string, and value set to 33218898 in the Partition Key Value text box, and then click Execute.

The following result is returned

```JSON
{
    "id": "3",
    "productId": "33218898",
    "description": "Contoso microfleece zip-up jacket",
    "price": "44.99",
    "_rid": "I2YsALxG+-EDAAAAAAAAAA==",
    "_self": "dbs/I2YsAA==/colls/I2YsALxG+-E=/docs/I2YsALxG+-EDAAAAAAAAAA==/",
    "_etag": "\"0000874e-0000-1a00-0000-5ca7a7050000\"",
    "_attachments": "attachments/"
}
```

David Papkin

**Comment by dpapkin** [comment]
Solved. Partition key name is case sensitive /Should be /productID, I had made is /productid. 

David Papkin
